<?php
if (!defined('_GNUBOARD_')) exit;
$data=array (
  'nav' => '1',
  'cache' => '',
  'bo_new' => '',
  'new' => '',
  'rank' => '',
  'target' => '',
  'bo_name' => '',
  'round' => '3',
  'thumb_w' => '',
  'thumb_h' => '',
  'thumb_d' => '',
  'margin' => '',
  'padding' => '',
  'xl' => '1',
  'lg' => '1',
  'md' => '1',
  'sm' => '1',
  'xs' => '1',
  'gr_list' => '',
  'bo_list' => 'dumy',
  'ca_list' => '',
  'mb_list' => '',
  'rows' => '',
  'page' => '',
  'sort' => '',
  'term' => '',
  'dayterm' => '',
);